- defaults:
    link:
      create: true
      force: false

- shell:
    - "[[ ! -e ~/.zshenv ]] && cp -v zshenv.example ~/.zshenv"

- link:
    ~/.localrc:
      ignore-missing: true
    ~/.p10k.zsh:
    ~/.profile:
    ~/.zinit/plugins/_local---config: config
    ~/.zshrc:
