# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &usr_cfeeley 30E9837DEE4C61CEA2EE557F447AEA2544F1E68F
  - &srv_workstation_age age1ugptt4756mkr29ysj342my7rmlljgde0vk8rt7kx32duz6j80c7scmky5n
  - &srv_macbook_pro_age age1ew69tycc7hqsfpldeq334dk9rhw5cup5ymyjnp2e22g5a6av4svqqm8xyk
creation_rules:
  - path_regex: ^secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *srv_workstation_age
      - *srv_macbook_pro_age
    - pgp:
      - *usr_cfeeley
