keys:
  - &user_cfeeley 69037A8C3B7036FFA2F8AFFF77CB2390C53B4E5B
  - &host_workstation age1ugptt4756mkr29ysj342my7rmlljgde0vk8rt7kx32duz6j80c7scmky5n
  - &host_macbook_pro age1ulg47luxtqsz7n27zl7v4wvrhx38y7mkmcmg73h4sh7sdwxyjqrquuz6g8
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_cfeeley
    - age:
      - *host_workstation
      - *host_macbook_pro
  - path_regex: secrets/azmidi/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_cfeeley
    - age:
      - *host_workstation
      - *host_macbook_pro
