format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$nodejs\
$php\
$python\
$ruby\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$cmd_duration\
$custom\
$line_break\
$jobs\
$time\
$status\
$character"""

# [directory]
# # truncate_to_repo = false
# truncation_length = 1
# fish_style_pwd_dir_length = 1

[git_branch]
style = "green"

[time]
disabled = false
