{
  # Table with all framework wrappers and the OSX releases where they are
  # first supported, and where support was removed. The introduced column
  # is ``null`` when the framework is supported on OSX 10.4 or later. The
  # removed column is ``null`` when the framework is present ont he latest
  # supported OSX release.
  FRAMEWORK_WRAPPERS = [
    # Name                      Introduced          Removed
    { name = "libdispatch"; introduced = "10.8"; removed = null; }
    { name = "Accessibility"; introduced = "11.0"; removed = null; }
    { name = "AdServices"; introduced = "11.0"; removed = null; }
    { name = "AdSupport"; introduced = "10.14"; removed = null; }
    { name = "AppTrackingTransparency"; introduced = "11.0"; removed = null; }
    { name = "AudioVideoBridging"; introduced = "10.8"; removed = null; }
    { name = "AuthenticationServices"; introduced = "10.15"; removed = null; }
    { name = "AutomaticAssessmentConfiguration"; introduced = "10.15"; removed = null; }
    { name = "AVKit"; introduced = "10.9"; removed = null; }
    { name = "AVFoundation"; introduced = "10.7"; removed = null; }
    { name = "AVRouting"; introduced = "13.0"; removed = null; }
    { name = "Accounts"; introduced = "10.8"; removed = null; }
    { name = "AddressBook"; introduced = null; removed = null; }
    { name = "AppleScriptKit"; introduced = null; removed = null; }
    { name = "AppleScriptObjC"; introduced = "10.6"; removed = null; }
    { name = "ApplicationServices"; introduced = null; removed = null; }
    { name = "Automator"; introduced = null; removed = null; }
    { name = "BackgroundAssets"; introduced = "13.0"; removed = null; }
    { name = "BusinessChat"; introduced = "10.14"; removed = null; }
    { name = "CFNetwork"; introduced = null; removed = null; }
    { name = "CalendarStore"; introduced = "10.5"; removed = null; }
    { name = "CallKit"; introduced = "11.0"; removed = null; }
    { name = "ClassKit"; introduced = "11.0"; removed = null; }
    { name = "CloudKit"; introduced = "10.10"; removed = null; }
    { name = "Cocoa"; introduced = null; removed = null; }
    { name = "Collaboration"; introduced = "10.5"; removed = null; }
    { name = "ColorSync"; introduced = "10.13"; removed = null; }
    { name = "Contacts"; introduced = "10.11"; removed = null; }
    { name = "ContactsUI"; introduced = "10.11"; removed = null; }
    { name = "CoreAudio"; introduced = null; removed = null; }
    { name = "CoreAudioKit"; introduced = null; removed = null; }
    { name = "CoreBluetooth"; introduced = "10.10"; removed = null; }
    { name = "CoreData"; introduced = null; removed = null; }
    { name = "CoreHaptics"; introduced = "10.15"; removed = null; }
    { name = "CoreLocation"; introduced = "10.6"; removed = null; }
    { name = "CoreMedia"; introduced = "10.7"; removed = null; }
    { name = "CoreMediaIO"; introduced = "10.7"; removed = null; }
    { name = "CoreMIDI"; introduced = null; removed = null; }
    { name = "CoreML"; introduced = "10.13"; removed = null; }
    { name = "CoreMotion"; introduced = "10.15"; removed = null; }
    { name = "CoreServices"; introduced = null; removed = null; }
    { name = "CoreSpotlight"; introduced = "10.13"; removed = null; }
    { name = "CoreText"; introduced = null; removed = null; }
    { name = "CoreWLAN"; introduced = "10.6"; removed = null; }
    { name = "CryptoTokenKit"; introduced = "10.10"; removed = null; }
    { name = "DataDetection"; introduced = "12.0"; removed = null; }
    { name = "DeviceCheck"; introduced = "10.15"; removed = null; }
    { name = "DictionaryServices"; introduced = "10.5"; removed = null; }
    { name = "DiscRecording"; introduced = null; removed = null; }
    { name = "DiscRecordingUI"; introduced = null; removed = null; }
    { name = "DiskArbitration"; introduced = null; removed = null; }
    { name = "DVDPlayback"; introduced = null; removed = null; }
    { name = "EventKit"; introduced = "10.8"; removed = null; }
    { name = "ExceptionHandling"; introduced = null; removed = null; }
    { name = "ExecutionPolicy"; introduced = "10.15"; removed = null; }
    { name = "ExternalAccessory"; introduced = "10.13"; removed = null; }
    { name = "ExtensionKit"; introduced = "13.0"; removed = null; }
    { name = "FileProvider"; introduced = "10.15"; removed = null; }
    { name = "FileProviderUI"; introduced = "10.15"; removed = null; }
    { name = "FSEvents"; introduced = "10.5"; removed = null; }
    { name = "FinderSync"; introduced = "10.10"; removed = null; }
    { name = "GameCenter"; introduced = "10.8"; removed = null; }
    { name = "GameController"; introduced = "10.9"; removed = null; }
    { name = "HealthKit"; introduced = "13.0"; removed = null; }
    { name = "IMServicePlugIn"; introduced = "10.7"; removed = null; }
    { name = "InputMethodKit"; introduced = "10.5"; removed = null; }
    { name = "ImageCaptureCore"; introduced = "10.6"; removed = null; }
    { name = "Intents"; introduced = "10.12"; removed = null; }
    { name = "IntentsUI"; introduced = "12.0"; removed = null; }
    { name = "InstallerPlugins"; introduced = null; removed = null; }
    { name = "InstantMessage"; introduced = "10.5"; removed = null; }
    { name = "IOBluetooth"; introduced = null; removed = null; }
    { name = "IOBluetoothUI"; introduced = null; removed = null; }
    { name = "IOSurface"; introduced = "10.6"; removed = null; }
    { name = "KernelManagement"; introduced = "11.0"; removed = null; }
    { name = "LatentSemanticMapping"; introduced = null; removed = null; }
    { name = "LaunchServices"; introduced = null; removed = null; }
    { name = "LinkPresentation"; introduced = "10.15"; removed = null; }
    { name = "LocalAuthentication"; introduced = "10.10"; removed = null; }
    { name = "LocalAuthenticationEmbeddedUI"; introduced = "12.0"; removed = null; }
    { name = "MailKit"; introduced = "12.0"; removed = null; }
    { name = "MapKit"; introduced = "10.9"; removed = null; }
    { name = "MediaAccessibility"; introduced = "10.9"; removed = null; }
    { name = "MediaLibrary"; introduced = "10.9"; removed = null; }
    { name = "MediaPlayer"; introduced = "10.12"; removed = null; }
    { name = "MediaToolbox"; introduced = "10.9"; removed = null; }
    { name = "Metal"; introduced = "10.11"; removed = null; }
    { name = "MetalFX"; introduced = "13.0"; removed = null; }
    { name = "MetalKit"; introduced = "10.11"; removed = null; }
    { name = "MetalPerformanceShaders"; introduced = "10.13"; removed = null; }
    { name = "MetalPerformanceShadersGraph"; introduced = "11.0"; removed = null; }
    { name = "MetricKit"; introduced = "12.0"; removed = null; }
    { name = "MLCompute"; introduced = "11.0"; removed = null; }
    { name = "ModelIO"; introduced = "10.11"; removed = null; }
    { name = "MultipeerConnectivity"; introduced = "10.10"; removed = null; }
    { name = "NaturalLanguage"; introduced = "10.14"; removed = null; }
    { name = "NetFS"; introduced = "10.6"; removed = null; }
    { name = "Network"; introduced = "10.14"; removed = null; }
    { name = "NetworkExtension"; introduced = "10.11"; removed = null; }
    { name = "NotificationCenter"; introduced = "10.10"; removed = null; }
    { name = "OpenDirectory"; introduced = "10.6"; removed = null; }
    { name = "OSAKit"; introduced = null; removed = null; }
    { name = "OSLog"; introduced = "10.15"; removed = null; }
    { name = "PassKit"; introduced = "11.0"; removed = null; }
    { name = "PencilKit"; introduced = "10.15"; removed = null; }
    { name = "PHASE"; introduced = "12.0"; removed = null; }
    { name = "Photos"; introduced = "10.11"; removed = null; }
    { name = "PhotosUI"; introduced = "10.11"; removed = null; }
    { name = "PreferencePanes"; introduced = null; removed = null; }
    { name = "PubSub"; introduced = "10.5"; removed = "10.14"; }
    { name = "PushKit"; introduced = "10.15"; removed = null; }
    { name = "Quartz"; introduced = null; removed = null; }
    { name = "QuickLookThumbnailing"; introduced = "10.15"; removed = null; }
    { name = "ReplayKit"; introduced = "11.0"; removed = null; }
    { name = "SafetyKit"; introduced = "13.0"; removed = null; }
    { name = "SafariServices"; introduced = "10.11"; removed = null; }
    { name = "ScreenSaver"; introduced = null; removed = null; }
    { name = "ScreenTime"; introduced = "11.0"; removed = null; }
    { name = "ScriptingBridge"; introduced = "10.5"; removed = null; }
    { name = "Security"; introduced = null; removed = null; }
    { name = "SecurityFoundation"; introduced = null; removed = null; }
    { name = "SecurityInterface"; introduced = null; removed = null; }
    { name = "SearchKit"; introduced = null; removed = null; }
    { name = "ServiceManagement"; introduced = "10.6"; removed = null; }
    { name = "ShazamKit"; introduced = "12.0"; removed = null; }
    { name = "Social"; introduced = "10.8"; removed = null; }
    { name = "Speech"; introduced = "10.15"; removed = null; }
    { name = "SpriteKit"; introduced = "10.9"; removed = null; }
    { name = "StoreKit"; introduced = "10.7"; removed = null; }
    { name = "SyncServices"; introduced = null; removed = null; }
    { name = "SystemConfiguration"; introduced = null; removed = null; }
    { name = "WebKit"; introduced = null; removed = null; }
    { name = "GameKit"; introduced = "10.8"; removed = null; }
    { name = "GameplayKit"; introduced = "10.11"; removed = null; }
    { name = "SceneKit"; introduced = "10.7"; removed = null; }
    { name = "SharedWithYouCore"; introduced = "13.0"; removed = null; }
    { name = "SharedWithYou"; introduced = "13.0"; removed = null; }
    { name = "SoundAnalysis"; introduced = "10.15"; removed = null; }
    { name = "ScreenCaptureKit"; introduced = "12.3"; removed = null; }
    { name = "SystemExtensions"; introduced = "10.15"; removed = null; }
    { name = "ThreadNetwork"; introduced = "13.0"; removed = null; }
    { name = "UniformTypeIdentifiers"; introduced = "11.0"; removed = null; }
    { name = "UserNotifications"; introduced = "10.14"; removed = null; }
    { name = "UserNotificationsUI"; introduced = "11.0"; removed = null; }
    { name = "VideoSubscriberAccount"; introduced = "10.14"; removed = null; }
    { name = "VideoToolbox"; introduced = "10.8"; removed = null; }
    { name = "Virtualization"; introduced = "11.0"; removed = null; }
    { name = "Vision"; introduced = "10.13"; removed = null; }
    # iTunes library is shipped with iTunes, not part of macOS 'core'
    # Requires iTunes 11 or later, which is not available on 10.5
    { name = "iTunesLibrary"; introduced = "10.6"; removed = null; }
  ];
}
