[home]
domain = "home.arpa"

[home.ipv4]
address = "192.168.1.1"
prefixLength = 24

[tso]
domain = "TKTKTK"

[cubegarden]
domain = "cube.garden"

[ouroboros]
domain = "loop.garden"

[seadome]
domain = "seadome.net"
