[home]
domain = "home.arpa"

[home.ipv4]
address = "192.168.0.1"
prefixLength = 24

[hetzner]
domain = "hetzner.arpa"

[hetzner.ipv4]
address = "5.161.105.1"
prefixLength = 26

[hetzner.ipv6]
address = "fe80::1"
prefixLength = 64

[local]
domain = "test"

[tso]
domain = "TKTKTK"

[cubegarden]
domain = "cube.garden"

[ouroboros]
domain = "loop.garden"

[cfeeley]
domain = "cfeeley.org"

[tusecurewireless]
domain = "temple.edu"
