[home]
domain = "home.arpa"

[home.ipv4]
address = "192.168.0.1"
prefixLength = 24

[local]
domain = "test"

[tso]
domain = "TKTKTK"

[cubegarden]
domain = "cube.garden"

[ouroboros]
domain = "loop.garden"

[cfeeley]
domain = "cfeeley.org"

[tusecurewireless]
domain = "temple.edu"
