# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.4.20231102";
    src = fetchurl {
      url = "https://pypi.org/packages/source/H/HPI/HPI-0.4.20231102.tar.gz";
      sha256 = "sha256-V3lzJs17I3zwaDowngD0gr1t0zRlMnuE7QZeb4dlbXA=";
    };
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "1.0.4";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-s1o188TlwpUQEN3X5MxUlD/2CFCpEkWu83U9O+wg3VU=";
    };
  };
  fish-fifc = {
    pname = "fish-fifc";
    version = "2ee5beec7dfd28101026357633616a211fe240ae";
    src = fetchgit {
      url = "https://github.com/gazorby/fifc";
      rev = "2ee5beec7dfd28101026357633616a211fe240ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Nrart7WAh2VQhsDDe0EFI59TqvBO56US2MraqencxgE=";
    };
    date = "2023-08-12";
  };
  fish-replay = {
    pname = "fish-replay";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "replay.fish";
      rev = "1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-bM6+oAd/HXaVgpJMut8bwqO54Le33hwO9qet9paK1kY=";
    };
  };
  fzf-scripts = {
    pname = "fzf-scripts";
    version = "6ed0f371abc50f41e685ea2b7cd80d3efda1a0c4";
    src = fetchgit {
      url = "https://github.com/DanielFGray/fzf-scripts";
      rev = "6ed0f371abc50f41e685ea2b7cd80d3efda1a0c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6E34xiLnKRM5RzYALPgjXeeZ0K/eUjaHS4SrOgPFmhM=";
    };
    date = "2024-02-20";
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  kitty-bortflower-icons = {
    pname = "kitty-bortflower-icons";
    version = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
    src = fetchgit {
      url = "https://github.com/DinkDonk/kitty-icon.git";
      rev = "269c0f0bd1c792cebc7821f299ce9250ed9bcd67";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Vy+iLGnysrJMSLfkaYq15pb/wG4kIbfsXRrPgSc3OFs=";
    };
    date = "2022-08-01";
  };
  orgparse = {
    pname = "orgparse";
    version = "0.4.20231004";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/orgparse/orgparse-0.4.20231004.tar.gz";
      sha256 = "sha256-pOOK6tq/mYiw9npmrNCCedGCILy8QioSkGDCiQu6kaA=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "9868180a9583e81ee68dd271688d5fee54edd779";
    src = fetchFromGitHub {
      owner = "karlicoss";
      repo = "promnesia";
      rev = "9868180a9583e81ee68dd271688d5fee54edd779";
      fetchSubmodules = false;
      sha256 = "sha256-rICpVr8QE7kSFgs3xhSyi6Ot9p9WTyQU52THBo2h5Z0=";
    };
    date = "2024-01-10";
  };
  roots-trellis-cli = {
    pname = "roots-trellis-cli";
    version = "v1.11.1";
    src = fetchFromGitHub {
      owner = "roots";
      repo = "trellis-cli";
      rev = "v1.11.1";
      fetchSubmodules = false;
      sha256 = "sha256-mAyMp9iSftfIhW6Gm/6IUdd+SZiURUAb3gHrueO3ALo=";
    };
  };
  ssh-cmc = {
    pname = "ssh-cmc";
    version = "3f02fdafd45d8bbf4d63ecbdfa9e453ca3597660";
    src = fetchgit {
      url = "https://github.com/TimidRobot/cmc";
      rev = "3f02fdafd45d8bbf4d63ecbdfa9e453ca3597660";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WofeUelyh8zUByqSoH49SzdAptjibnXfwKk0dvuSjoc=";
    };
    date = "2023-05-18";
  };
}
