[hosts.tapestone]
network = "tso"

[hosts.tapestone.ipv4]
address = "94.130.220.154"
cidr = "26"
gateway = "94.130.220.129"

[hosts.tapestone.ipv6]
addresses = []
subnet = "2a01:4f8:13b:17ac::/64"
cidr = "64"
gateway = "fe80::1"
