[hosts.tapestone]
network = "tso"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICdk0EzvFodiLIxxheOWQTAav92uZwfMVR1k/0TS7yal root@tapestone",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfO/9X2TwY26GTRrc2OT1GemedLzdagzxfAX+6ZIZAjOCiY0g3znU3uPictDVZy+Gz8vEpK52h/g8b/ZMu89SlqRgw5cVffHY+snit7rziTzX0tITZvvooZN2nmmwlVjhZn0pl2oiLLuBfWPrDj40bmVoBZE4xKfYSbM9T+ZLT0oP0gYlZ8yVGsQdclELUp7z7dDZ0y5aUwyOw3IXnt3lLsW8notRR5n18Nm1gyARCmVWa0cuHwbfEGv9NmIKY8/ydtC+poISTbGj+GGIqimPDfIS00rafCeoLSNnodjtDIxklxyhgmnQKKEddbdPk3c7nDtImSgnbvxhYe3P3QWp6XEdFlajer6WzDcaCe8V0loF4XDueRGut7Q9JkVZwvIX3s9DwJjL3W/EpkbrYu1I76dvsExTcZIRqrxA3B376oJsmLpn9/Y/lak6awqmbpW3w5M8Nxfyw/CxcVJ/M1J4dsxwyHEL1bRcYlOxsOmSqqcnGDyNIdOsNcwDxWEyeN1OCnDjgIv7vKU/BXk1ZO+/bL8OAz/yBZErM3BvMP4VYGq7y0sNNQ7DKOy4EH7pncD/2JecrQ4j0m0idCp4Gx2IlWn4nKlLJer09Hi0BOlMU50efqk9PRc1KP3Po54HFaLsYSd1rGyPZE3JQ0CxNh/MUDmU3++gOkcQKLge/i1W5sQ== root@tapestone",
]

[hosts.tapestone.ipv4]
address = "94.130.220.154"
cidr = "26"
gateway = "94.130.220.129"

[hosts.tapestone.ipv6]
addresses = []
subnet = "2a01:4f8:13b:17ac::/64"
cidr = "64"
gateway = "fe80::1"
