# espanso configuration file

matches:
  - trigger: ":s.cmd"
    replace: "⌘"

  - trigger: ":s.shift"
    replace: "⇧"

  - trigger: ":s.ctrl"
    replace: "⌃"

  - trigger: ":s.shift"
    replace: "⌥"

  - trigger: ":s.a.l"
    replace: "←"

  - trigger: ":s.a.r"
    replace: "→"

  - trigger: ":s.a.u"
    replace: "↑"

  - trigger: ":s.a.d"
    replace: "↓"

  - trigger: ":s.esc"
    replace: "⎋"

  - trigger: ":s.null"
    replace: "∅"
