name: "Build & Cachix"
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v10
      with:
        name: dotfield
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: dotfield,nix-community,nrdxp
    - run: nix -Lv flake check
    - run: nix -Lv build ".#ghaDarwin"
