name: "Build & Cachix"
on:
  push:
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            type: darwin
            hostname: ci-darwin
          - os: ubuntu-latest
            type: nixos
            hostname: ci-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: dotfield
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: dotfield,nix-community,nrdxp
      - run: nix -Lv flake show --show-trace
      - run: nix -Lv flake check --show-trace
      # TODO: revise this so it's more useful and less prone to unexpected failures missed by checks
      # run: nix -Lv build ".#${{ matrix.type }}Configurations.${{ matrix.hostname }}.config.system.build.toplevel" --show-trace
